### ISSUE TITLE
Feedback on staging.

### ISSUE THREAD

**Issue by sebastienvercammen** [HackLeague/hackleague#1]
Hey guys, how's everyone doing ;) Glad to see an email in my inbox from Hack League!

First off, the current staging is good. 👍 I can see where you're going with it, and you guys have a lot of potential.

Here are my thoughts on the current version. I know the focus is on the technical aspect of the challenge and things like job description/content don't seem as important yet, but they will eventually be so I've included those:

* Once in a while, loading the page got stuck on "Loading". I've had it happen three times, but when I now try to reproduce the steps it doesn't happen again. Could be server related.
* Loading the page could be faster. e.g. compressing bundle.staging.js would save 2.7MiB (78%).
* The link in the email leads to `/campaign/5/challenge`. Linking it to `/campaign/5/job` would make the point of the platform clearer. First we'd see the job (the "reward"), then we're directed towards the challenge we need to complete to get it. Game design principles.
* Typography can use some work! You're presenting a lot of information in a vertical list at the moment, but it all looks alike because it uses the same fonts, same font sizes, same colors, and there's little spacing in between the different blocks. Changing font styles to better present information will help make your website a lot clearer and more enjoyable to read. Here are some examples (not the best, but I don't have my usual list with me today): [mojotech toolkit](https://www.mojotech.com/toolkit), [Jason James](http://jasonjam.es/), [1910](http://weare1910.com/about/), [Cultivated Wit](http://www.cultivatedwit.com/).
* Rather than letting "Your challenge" only be a tab at the top, there should be a clear call-to-action in the "Job description" itself, to give the experience of reading the job description (= reward), scrolling down, and getting a button to click to "Start your challenge!".
* At the bottom of the job description, you have 4 lines of text just to describe the starting time and duration. This information should be at the top of the page and shouldn't be presented with so much descriptive text.
* In the footer, the text "Hack League" should be a link to your website.
* Legal notes: missing EU Cookie disclaimer, Privacy Policy and Terms and Conditions.

Overall, the experience could be presented in a more exciting way. You have interesting tech and a fun/interesting/game design approach to solving the problem of recruitment in tech fields, but the presentation still needs to catch up to the tech.

The average person (especially  HR) doesn't have the knowledge or experience to extract the value of the tech from the current design. Overwhelm them with an awesome presentation, and they'll trust your tech.

Unfortunately I don't have the time to test the tech itself, but I'm sure you guys will handle it. 👍

**Comment by maxcz** [comment]
Thx a lot Seb!!
Always valuable insights 👍 
Will definitely help us improve. 

Hope all is going well on your side.

**Comment by xurei** [comment]
Hey Sebastien ! Thank you for your quick feedback ! Glad to hear you like it ^_^

Overall, we agree to everything you said above. Thanks for the examples for the typography. We'll take a look on that.

About the loading problem, if you experiment it again, could you fill in an issue with the steps that you took ?

Again, thank you very much for your input ! It's really important for us to create something developers like, and your feedback helps us a lot in that direction.
